name: build
on: [push]

jobs:
  test:
    name: Run Tests and Code Coverage 📝
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} 🐍
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies ⚙️
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest
    - name: Test with pytest ✅
      run: |
        pytest

  publish:
    name: Publish Nightly 🚀
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 🐍
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies ⚙️
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Set alpha version
      run: sed -i "/^version = /s/$/a$(git rev-parse --short HEAD)/" setup.cfg
    - name: Build a binary wheel and a source tarball 🚧
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish to Test PyPI 📦
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
